### PR TITLE
Add gd translation

### PR DESCRIPTION
**Pull request by gunchleoc**
Translation for Scottish Gaelic

BTW `Enter's the instance's address` should be `Enter the instance's address`

### CODE REVIEW

**Comment by kimsible** [comment]
Thanks for the addition ! You must add the file in `package.json` too, like this : https://github.com/kimsible/peertube-plugin-social-sharing/blob/b4504243d8aa60a9988343592160cf80a4013a02/package.json#L79

**Comment by gunchleoc** [comment]
> Thanks for the addition ! You must add the file in `package.json` too, like this :
> 
> https://github.com/kimsible/peertube-plugin-social-sharing/blob/b4504243d8aa60a9988343592160cf80a4013a02/package.json#L79

Done. Sorted them alphabetically too - this will make management easier if you get a lot of languages in the future.

I hope I didn't mess up the `,`, JSON is 0 tolerance on that...

**Comment by kimsible** [comment]
Thanks ! Are you sure the country code is not `gd_GB` ?

**Comment by kimsible** [comment]
> BTW  Enter's the instance's address should be Enter the instance's address

I will correct this just after merging.

**Comment by gunchleoc** [comment]
We usually don't add the country code & just use the generic locale for Gaelic. The chance that one could want to create e.g. a separate `gd_CA` translation is virtually nonexistent.

**Comment by kimsible** [comment]
Thanks for the details @gunchleoc ! don't hesitate to comment here if you see any issues with the new releases, the 0.9.1 adds the translation gd

**Comment by gunchleoc** [comment]
Thanks for the plugin!

I am not running a server, so it's hard for me to test without knowing who is using the plugin.

**Pull request merged**
